### ISSUE TITLE
Mod doesnt work :( - tested 

### ISSUE THREAD

**Issue by Negativfraction** [TobbyTheBobby/TobbertMods#1]
Hi and firstly thanks for your efforts on the above, i am genuinely really looking forward to getting this working.

I picked the game up this week and i am not new to modding, i have done this via the thunderstore and it breaks the game, other mods are working fine and if i install just mod this then it fails. 

I thought it may be the dependencies, but timber api and bepinexpack_timberborn run other mods fine.

bepinexpack_timberborn throws this error when trying to start a new game

If its me and there is something simple i am not doing then apologies, if it isnt i hope this helps others get the game running.

[Error  : Unity Log] TypeLoadException: Could not load type of field 'AutomaticBeaverMigration.AutomaticBeaverMigrationUI:_tooltipRegistrar' (14) due to: Could not resolve type with token 01000028 from typeref (expected class 'Timberborn.CoreUI.TooltipRegistrar' in assembly 'Timberborn.CoreUI, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Timberborn.CoreUI, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Timberborn.CoreUI.TooltipRegistrar member:(null)
Stack trace:
System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) (at <6073cf49ed704e958b8a66d540dea948>:0)
System.RuntimeType.IsAssignableFrom (System.Type c) (at <6073cf49ed704e958b8a66d540dea948>:0)
Bindito.Core.Internal.MultiBindingService.IsMultiBound (System.Type parameterType, System.Type& multiBoundType) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.BindingResolver.TryGetBindings (System.Type type, System.Collections.Generic.IEnumerable`1[Bindito.Core.Internal.Binding]& bindings) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.BindingAnalyser.CheckForProblems (Bindito.Core.Internal.ProvisionBinding suspect) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.BindingAnalyser.CheckForProblems (Bindito.Core.Internal.ProvisionBinding suspect) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.BindingAnalyser.Analyse (System.Type suspectType, Bindito.Core.Internal.ProvisionBinding suspectProvisionBinding) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.BindingValidator.Validate (System.Type type, Bindito.Core.Internal.ProvisionBinding provisionBinding) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.BinderValidator.ValidateBindings () (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.BinderValidator.Validate () (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.ValidateConfiguration (Bindito.Core.Internal.IBindingValidator bindingValidator, Bindito.Core.Internal.IBinder binder) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.CreateContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.CreateChildContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.Container.CreateChildContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.Container.CreateChildContainer (Bindito.Core.IConfigurator[] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Unity.SceneConfigurator.CreateSceneContainer () (at <b39f4d0e163e4a6ebf49e6ec2b083479>:0)
Bindito.Unity.SceneConfigurator.Awake () (at <b39f4d0e163e4a6ebf49e6ec2b083479>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.MasterScene.MasterSceneLauncher+<Start>d__4.MoveNext () (at <40ff81f2e6ce4d60b3ba800d849ff0e2>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <646b0f30310f400a8a93a79d3cd89ad9>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.MasterScene.NewGameInitializer.Start () (at <40ff81f2e6ce4d60b3ba800d849ff0e2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.MasterScene.NewGameInitializer.Update () (at <40ff81f2e6ce4d60b3ba800d849ff0e2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.Benchmarking.BenchmarkStarter.Update () (at <8d7d128638144947bfb5b1eb28835652>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.MasterScene.NewGameInitializer.Update () (at <40ff81f2e6ce4d60b3ba800d849ff0e2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.Benchmarking.BenchmarkStarter.Update () (at <8d7d128638144947bfb5b1eb28835652>:0)

**Comment by TobbyTheBobby** [comment]
Nono, it indeed has to do with my mod. I had someproblems with it, when making it. Did u get the latest version and you are playing on the experimental version of the game?

**Comment by Negativfraction** [comment]
Thanks for the reply, not sure why GitHub didn't tell me!

I am on the latest version and i haven't got beta or experimental ticked in my steam options, just none.

Happy to complete any testing i can to help.

**Comment by TobbyTheBobby** [comment]
Aah, that explains it then. I only made the mod compatible for the experimental version of the game. You would have to upgrade to that or yoy have to wait for the experimental update to release as stable.

**Comment by Negativfraction** [comment]
Ah ok my bad i didn't notice that! I am just playing as the second race now, but i will enable it for the next game and give it a go.

Thanks for replying and letting me know :)

**Comment by TobbyTheBobby** [comment]
No problemo, GL with your games!
